Cache component query results
atopile/faebryk pull request #15
Opened 2024-08-17 04:28 UTC by mawildoer

python src/bikey_wagon/main.py  87.93s user 24.01s system 52% cpu 3:34.41 total with caching

python src/bikey_wagon/main.py  79.57s user 23.47s system 44% cpu 3:52.02 total without

No tangible difference.

# \<Prefix\>: \<Title\>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# Checklist

Please read and execute the following:

- [ ] My code follows the [coding guidelines](/faebryk/faebryk/blob/main/docs/CODING_GUIDELINES.md) of this project
- [ ] My PR title is following the [contribution guidelines](/faebryk/faebryk/blob/main/docs/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I ran [Black](../docs/CONTRIBUTING.md#creating-a-pull-request) to format my code

#### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](/faebryk/faebryk/blob/main/docs/CODE_OF_CONDUCT.md):

- [ ] I agree to follow this project's [Code of Conduct](/faebryk/faebryk/blob/main/docs/CODE_OF_CONDUCT.md)

2024-08-17 06:57 UTC, IoannisP-ITENG commented
Have you ran it with `./tools/profile.sh py pyinstrument <bikey-wagon>'?
Looks like most time is spent in the python part (not sql part). We can cache that too.

2024-08-17 15:24 UTC, mawildoer commented
Thanks for the link! I’ll give it another swing with the profiler when I
get the chance

On Fri, Aug 16, 2024 at 23:58 IoannisP-ITENG ***@***.***>
wrote:

> Have you ran it with `./tools/profile.sh py pyinstrument '?
> Looks like most time is spent in the python part (not sql part). We can
> cache that too.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/atopile/faebryk/pull/15#issuecomment-2294712800>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABALRKXHHXNGU67QJ5BOWWDZR3YAXAVCNFSM6AAAAABMVCLF6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJUG4YTEOBQGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-06 11:52 UTC, iopapamanoglou requested changes
This won't work like this, we need to do per filter caching.

2024-09-06 11:52 UTC, iopapamanoglou commented on src/faebryk/libs/picker/jlcpcb/jlcpcb.py
> +        query_hash = str(self.Q)
This does not work:
`<tortoise.expressions.Q object at 0x742078c0d4f0>`

2024-11-16 20:15 UTC, iopapamanoglou commented
Superseded by CachePicker

2024-11-16 20:15 UTC, closed without merging